# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Nate Yazdani
email: nyazdani@cs.washington.edu
description: My personal webpage
#footer_text: >
#  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
#  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: nateyazdani # put your github username
twitter_username: nate_yazdani # put your twitter username
#scholar_authorid: # put your google scholar author id

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: research blog
blog_description: notes from my research

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'newer'
    older: 'older'

# Comments
#disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
- news
- projects

news_limit: 5
post_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
gems:
- jekyll-paginate
- jekyll/scholar
- jemoji

# Jekyll-Scholar
scholar:
  last_name: Yazdani
  style: _data/acm-toplas.csl
  sort_by: year
  order: descending
  bibliography_template: "{{ reference | replace: 'Nathaniel Yazdani', '<b>Nathaniel Yazdani</b>' }} [<a href='{{ links.pdf }}'>PDF</a>]"
  repository: assets/pdf/

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
